[project]
name = "mlops-e1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

[tool.poetry.dependencies]
python = ">=3.12"
fastapi = { version = ">=0.115.7", extras = ["standard"] }
gymnasium = ">=1.0.0"
ipykernel = ">=6.29.5"
stable-baselines3 = ">=2.5.0"
torch = ">=2.5.1"
websockets = ">=14.2"
